### PR TITLE
Frosty1 compatch

### PR DESCRIPTION
**Pull request by TheDovahkiin97**

### CODE REVIEW

**Comment by TheDovahkiin97** [comment]
if you have the time you could check if there are any redundant szekely localisations

**Comment by TheDovahkiin97** [comment]
ok it seems like i failed somewhere after compatching this motherfucker for 8hrs because some CoAs are wrong

**Comment by TheDovahkiin97** [comment]
somehow there are 17 baronies more here somewhere

**Comment by TheDovahkiin97** [comment]
ok everything fine now. from my pov its ready to merge

**Comment by hmlendea** [comment]
I am still away on holiday but it looks good.
I will look more into redundant names and remove them later if need be, but until them they won't cause issues anyway.

**Comment by hmlendea** [comment]
Does Steam let you update the mod on the workshop?

**Comment by TheDovahkiin97** [comment]
no i can only publish it as a new mod

**Comment by hmlendea** [comment]
I will be back from holiday tomorrow and I'll update the mod on Steam.
(CK2 doesn't work on my laptop)

**Pull request merged**
